name: cmark
description: Dart bindings for libcmark (CommonMark parser)
version: 0.0.1
author: Manabu Nakazawa <mshibanami@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  markdown: ^2.0.3
  test: ^1.0.0
